# Generated by Django 3.2.6 on 2021-08-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
