# Generated by Django 3.2.6 on 2021-08-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stable',
            name='id',
        ),
        migrations.AddField(
            model_name='stable',
            name='test',
            field=models.CharField(default='mandaotry', max_length=54),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stable',
            name='shivani',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.rtable'),
        ),
    ]
