# Generated by Django 3.2.5 on 2021-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Contact', models.IntegerField()),
                ('Messages', models.CharField(max_length=200)),
            ],
        ),
    ]
